---
---

## Exercise solutions

===

## Solution 1

First solution:

```{r title="{{ site.handouts }}"}
x <- (-0.3 + sqrt(0.3 ^ 2 - 4 * 1.5 * -2.9)) / (2 * 1.5)
```

```{r}
1.5 * x^2 + 0.3 * x - 2.9
```

Second solution:

```{r title="{{ site.handouts }}"}
x <- (-0.3 - sqrt(0.3 ^ 2 - 4 * 1.5 * -2.9)) / (2 * 1.5)
```

```{r}
1.5 * x^2 + 0.3 * x - 2.9
```

<aside class="notes" markdown="block">
[Return](#exercise-1)
</aside>

===

## Solution 2

```{r title="{{ site.handouts }}"}
x <- list(1, list(2, 3))
y <- c(1, list(2, 3))
```

```{r}
str(x)
```
```{r}
str(y)
```

The variable `x` contains two elements, a number and a list. The variable `y` has concatenation of the two arguments, coerced to the more flexible of the two (a list is more flexible than a number). Both `x` and `y` are lists.

<aside class="notes" markdown="block">
[Return](#exercise-2)
</aside>

===

## Solution 3

```{r title="{{ site.handouts }}"}
species <- c()
abund <- c()
data <- data.frame(species, abund)
```

```{r}
str(data)
```

<aside class="notes" markdown="block">
[Return](#exercise-3)
</aside>

===

## Solution 4

```{r title="{{ site.handouts }}"}
surveys <- read.csv('data/surveys.csv', stringsAsFactors = FALSE, na.strings = '')
surveys$sex <- factor(surveys$sex)
```

```{r}
str(surveys)
```

<aside class="notes" markdown="block">
[Return](#exercise-4)
</aside>

===

## Solution 5

```{r title="{{ site.handouts }}"}
sol5a <- days[c(-1, -7)]
sol5b <- days[seq(2, 7, 2)]
```

```{r}
sol5a
```

```{r}
sol5b
```

<aside class="notes" markdown="block">
[Return](#exercise-5)
</aside>

===

## Solution 6

```{r title="{{ site.handouts }}"}
sol6 <- df[2:3, 'ed']
```

```{r}
sol6
```

<aside class="notes" markdown="block">
[Return](#exercise-6))
</aside>

===

## Solution 7

```{r title="{{ site.handouts }}"}
first <- function(dat) {
    if (is.vector(dat)) {
        result <- dat[1]
    } else if (is.matrix(dat)) {
        result <- dat[1, 1]
    } else {
        result <- dat[1, ]
    }
    return(result)
}
```

```{r}
m <- matrix(1:9, nrow = 3, ncol = 3)
first(m)
```

<aside class="notes" markdown="block">
[Return](#exercise-7)
</aside>

===

## Solution 8

```{r title="{{ site.handouts }}"}
surveys.hl_model <- lm(log(hindfoot_length) ~ log(weight), data = surveys)
```

```{r}
coef(surveys.hl_model)[2]
```

<aside class="notes" markdown="block">
[Return](#exercise-8)
</aside>
